Remove webdrivers gem, which has no support for Chrome v115
owen2345/camaleon-cms pull request #1060
Opened 2023-07-26 07:17 UTC by texpert

Selenium itself will be automatically managing both browsers and drivers, which is pretty exciting - see https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1648154088

2023-07-27 22:59 UTC, brian-kephart requested changes
@texpert that's great news! Since that's a new selenium feature, can we add a version constraint to selenium? Based on that comment, it seems like it should be `>= 4.11.0`

I've also investigated migrating the tests from selenium to Cuprite. When I tried it, though, it broke a few tests and did not run faster, so I never made a PR. If we start having problems beyond this, I might revisit that approach. For now though, sticking with selenium seems best.

2023-07-28 09:05 UTC, texpert commented
> 

@brian-kephart, I don't think it reasonable to set versions restrictions, except when temporarily not allowing a certain version to be used because of some issues. Let the `bundler` do its work is the best practice, in general.

Also, `selenium-webdriver` is still at the 4.10 version, but this is actually working, as stated on the `webdrivers` discussion:

"Updating to Selenium 4.10 and removing this gem is essentially doing the same as point 2 - you can set the required version for chromedriver to v114 and it will work for Chrome v115 (but will break for Chrome v116)"

Moreover, the 4.11 version of `selenium-webdriver` will require Ruby 3.xx version, so it will come as a breaking change.

2023-07-28 17:59 UTC, brian-kephart commented
@texpert I largely agree with you. And yeah, if this will be changing over the next few versions of Chrome, then a constraint would just cause more problems than it would solve.

2023-07-28 17:59 UTC, brian-kephart approved these changes

2023-07-28 20:44 UTC, merged